/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete_interfaz;

/**
 *
 * @author Admin
 */
public class Interfaz_usuario_bank extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_usuario_bank
     */
    public Interfaz_usuario_bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton_registro_usuario = new javax.swing.JButton();
        boton_crear_cuenta = new javax.swing.JButton();
        boton_retiros = new javax.swing.JButton();
        boton_depositos = new javax.swing.JButton();
        boton_cuentas_registradas = new javax.swing.JButton();
        boton_historial_transaccion = new javax.swing.JButton();
        boton_reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENIDO <ADMINISTRADOR>");

        boton_registro_usuario.setText("Registro Usuario");
        boton_registro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registro_usuarioActionPerformed(evt);
            }
        });

        boton_crear_cuenta.setText("Crear Cuenta ");
        boton_crear_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crear_cuentaActionPerformed(evt);
            }
        });

        boton_retiros.setText("Retiros ");

        boton_depositos.setText("Depositos ");

        boton_cuentas_registradas.setText("Buscar Cuenta Asociadas");
        boton_cuentas_registradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cuentas_registradasActionPerformed(evt);
            }
        });

        boton_historial_transaccion.setText("Historial de Transiccion");

        boton_reportes.setText("Generacion de Reportes ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(boton_registro_usuario)
                        .addGap(52, 52, 52)
                        .addComponent(boton_crear_cuenta)
                        .addGap(50, 50, 50)
                        .addComponent(boton_historial_transaccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(boton_depositos)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_cuentas_registradas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_reportes)
                                .addGap(48, 48, 48)
                                .addComponent(boton_retiros)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_crear_cuenta)
                    .addComponent(boton_registro_usuario)
                    .addComponent(boton_historial_transaccion))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_reportes)
                    .addComponent(boton_depositos)
                    .addComponent(boton_retiros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(boton_cuentas_registradas)
                .addGap(153, 153, 153))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registro_usuarioActionPerformed
       Ventana_registro_usuario ingresar_ventana = new Ventana_registro_usuario();
       ingresar_ventana.setVisible(true);
       this.setVisible(false); // Ocultar la ventana principal (si lo deseas)
    }//GEN-LAST:event_boton_registro_usuarioActionPerformed

    private void boton_cuentas_registradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cuentas_registradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_cuentas_registradasActionPerformed

    private void boton_crear_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crear_cuentaActionPerformed
        //VAMOS A IR A LA VENTANA CREAR CUENTA 
        Ventana_crear_cuenta ventana_crear = new Ventana_crear_cuenta();
       ventana_crear.setVisible(true);
       this.setVisible(false); // Ocultar la ventana principal (si lo deseas)
    }//GEN-LAST:event_boton_crear_cuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_usuario_bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_usuario_bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_usuario_bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_usuario_bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_usuario_bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_crear_cuenta;
    private javax.swing.JButton boton_cuentas_registradas;
    private javax.swing.JButton boton_depositos;
    private javax.swing.JButton boton_historial_transaccion;
    private javax.swing.JButton boton_registro_usuario;
    private javax.swing.JButton boton_reportes;
    private javax.swing.JButton boton_retiros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
